# An example of the config file used
# Host that the server is listening on
address = "0.0.0.0"
# Port the server is listening on
port = 8080
# The client Public Key
public_key = "abc"
# The client Private Key
private_key = "abc"
# The Root Certificate for the client & server
ca_certificate = "abc"
